# Generated by Django 5.1.5 on 2025-01-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobAppOrganizer', '0002_resume_is_master_alter_resume_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=85),
        ),
        migrations.AlterField(
            model_name='resume',
            name='template_file',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
